### ISSUE TITLE
T-2: Create unit tests for each of the  features of sprint 1-2

### ISSUE THREAD

**Issue by CybRam** [charlotteglen/WIZARD7-SOEN341_Project_F24#23]
### Goal:

- Create unit tests for all the features in sprint 1 and 2
- ensure that these tests run automatically

### Priority:

LOW

### Estimate:

5 story points

**Comment by Youveng** [comment]
Completed

Sprint 1: 
![image](https://github.com/user-attachments/assets/242578ee-fec6-4c7d-a89f-f5e455d704f4)

Sprint 2:
![image](https://github.com/user-attachments/assets/ebb03785-e19e-4067-820d-f07d30dd7143)
