### ISSUE TITLE
US-5 Testing the database

### ISSUE THREAD

**Issue by TimmyTwoTimes** [charlotteglen/WIZARD7-SOEN341_Project_F24#6]
**Narrative:**
As a User,
I want the database system not to have errors
so that the upload, retrieval of the data can be completed efficiently
.
**Acceptance Criteria:**

1. The data are sent smoothly to the database
2. The data needed are retrieved from the database
3. The data is safely stored in the database.

**Priority:**
MEDIUM

**Estimate:**
5 story points

**Definition Of Done**

- [ ] uploading the data smoothly
- [ ] retrieving the data smoothly
- [ ] data stored safely on the database

**Comment by Youveng** [comment]
Database all good
