### ISSUE TITLE
US-6: Importing a course roster  from a CSV file

### ISSUE THREAD

**Issue by CybRam** [charlotteglen/WIZARD7-SOEN341_Project_F24#8]
### Narrative:

As a teacher,
I want to be able to import a course roster by uploading a csv file,
so that I can setup the teams automatically.

### Acceptance criteria:

1. The user can access the import option in their dashboard.
2. The user can upload any csv file to the website.
3. The group distributions should be performed after the file is uploaded and read.

### Priority:

HIGH

### Estimate:

3 story points

### Definition of done

- [ ] Code is written, reviewed, and merged into the main branch.
- [ ] All acceptance criteria are met and tested.
- [ ] The feature is viewed and validated by the TA during demo.

**Comment by CybRam** [comment]
@anyone feel free to modify the acceptance criteria id you feel like I missed any.

**Comment by Youveng** [comment]
Export/Import CSV good
